# Generated by Django 2.0.2 on 2018-02-12 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retrouser',
            name='user',
        ),
        migrations.DeleteModel(
            name='RetroUser',
        ),
    ]
